### ISSUE TITLE
KeyError 'url'

### ISSUE THREAD

**Issue by PhuriousGeorge** [benediktg/wallabag-migration#2]
Thanks for this script however I can't seem to get past this error:

```
Traceback (most recent call last):
  File "./post-articles.py", line 106, in <module>
    main(sys.argv)
  File "./post-articles.py", line 24, in main
    article = extractArticle(row, token)
  File "./post-articles.py", line 79, in extractArticle
    url = row['url']
```

**Comment by pasbec** [comment]
You have most probably dropped the fieldnames in your csv file. The way the `csv.dictReader(...)` is constructed in `post-articles.py` makes this mandatory. Make sure the first line of your CSV-file only contains the following:

``` csv
url, is_read, is_fav
```

and nothing else.

By the way, I had to change the `get`

``` python
r = requests.get('{}/oauth/v2/token'.format(hostname), payload)
```

 in line 65 to `post`

``` python
r = requests.post('{}/oauth/v2/token'.format(hostname), payload)
```

in order to make it work.

In case of self-signed SSL-certificates, you can further replace in line 26

``` python
r = requests.post('{}/api/entries.json'.format(hostname), article)
```

with

``` python
r = requests.post('{}/api/entries.json'.format(hostname), article, verify=False)
```

and in line 65 replace

``` python
r = requests.get('{}/oauth/v2/token'.format(hostname), payload)
```

with

``` python
r = requests.post('{}/oauth/v2/token'.format(hostname), payload, verify=False)
```

.

Best,
Pascal

**Comment by benediktg** [comment]
@pasbec Is it better now (in the `issue-2` branch)?

**Comment by PhuriousGeorge** [comment]
My CSV was clean, though I did find some bad "links" from the MySQL export.  I wound up installing V1.92 locally and exporting chunks at a time and deleted my source data once complete, so I'm unable to test again.  Thanks for the replies though.

**Comment by benediktg** [comment]
@PhuriousGeorge Is it OK when I close this issue now?
